# Dependencies
#### markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Pine Designs
tagline:          'Well designed fun'
description:      'Well designed fun'
url:              https://pinedesigns.github.io
baseurl:          /

email:            booligoosh@optusnet.com.au

author:
  name:           'Booligoosh'
  url:            https://booligoosh.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pinedesigns/pinedesigns.github.io/

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - github-pages

zazzle:
    store: 'https://www.zazzle.com/pinedesigns?rf=238712509161080982&tc=pinedesignsgithubio'
    
    
img:
    logo:             /public/img/logo_trans.svg
    banner:           /public/img/banner.svg