# Dependencies
#### markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Pine Designs
title-colored:    '<span class="title-colored-pine">Pine</span> <span class="title-colored-designs">Designs</span>'
tagline:          'Fun never looked so good.'
description:      'Fun never looked so good.'
url:              
baseurl:          /

email:            pinedesigns.shop@gmail.com

contact:          /contact/

author:
  name:           'Booligoosh'
  url:            https://booligoosh.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pinedesigns/pinedesigns.github.io/

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - github-pages
  - jekyll-sitemap # leave at the end

zazzle:
    store:     'https://www.zazzle.com/pinedesigns?rf=238712509161080982&tc=pinedesignsgithubio'
    products:  'https://www.zazzle.com/pinedesigns/products?rf=238712509161080982&tc=pinedesignsgithubio'
    modern-pineapple: 'https://www.zazzle.com.au/collections/modern_pineapple-119235495781044968?rf=238712509161080982&tc=pinedesignsgithubio'

newsletter:    'https://bit.ly/pine_designs_newsletter_01'
    
postimg:       /public/img/post

img:
    logo:             /public/img/pine-designs-logo-transparent.svg
    banner:           /public/img/pine-designs-banner.svg