# Dependencies
#### markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Pine Designs
title-colored:    '<span class="title-colored-pine">Pine</span> <span class="title-colored-designs">Designs</span>'
tagline:          'Fun never looked so good.'
description:      'Fun never looked so good.'
url:              https://pinedesigns.github.io
baseurl:          
baseurlactual:    /

email:            pinedesigns.shop@gmail.com

contact:          /contact/

author:
  name:           'Booligoosh'
  url:            https://booligoosh.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pinedesigns/pinedesigns.github.io/

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - github-pages
  - jekyll-sitemap # leave at the end

zazzle:
    store:     'https://www.zazzle.com/pinedesigns?rf=238712509161080982&tc=pinedesignsgithubio'
    products:  'https://www.zazzle.com/pinedesigns/products?rf=238712509161080982&tc=pinedesignsgithubio'
    collections:
        modern-pineapple: 'https://www.zazzle.com.au/collections/modern_pineapple_range-119235495781044968?rf=238712509161080982&CMPN=share_dclit&lang=en&social=true'
        
        life-is-like-a-pineapple: 'https://www.zazzle.com.au/collections/life_is_like_a_pineapple_range-119380580491205535?rf=238712509161080982&CMPN=share_dclit&lang=en&social=true'
        
        hardcore-pineapple: 'https://www.zazzle.com.au/collections/hardcore_pineapple_range-119713769587531496?rf=238712509161080982&CMPN=share_dclit&lang=en&social=true'
        
        watercolor-pineapple: 'https://www.zazzle.com.au/collections/juicy_watercolor_pineapple_range-119616646632761195?rf=238712509161080982&CMPN=share_dclit&lang=en&social=true'

newsletter:    'https://bit.ly/pine_designs_newsletter_01'
    
postimg:       https://pinedesigns.github.io/public/img/post
imgdirectory:  https://pinedesigns.github.io/public/img

img:
    logo:             https://pinedesigns.github.io/public/img/pine-designs-logo-transparent.svg
    banner:           https://pinedesigns.github.io/public/img/pine-designs-banner.svg

contact:
    github: https://github.com/pinedesigns/
    