# Dependencies
#### markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Pine Designs
title-colored:    '<span class="title-colored-pine">Pine</span> <span class="title-colored-designs">Designs</span>'
tagline:          'Fun never looked so good.'
description:      'Fun never looked so good.'
url:              
baseurl:          /

email:            booligoosh@optusnet.com.au

author:
  name:           'Booligoosh'
  url:            https://booligoosh.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pinedesigns/pinedesigns.github.io/

gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - github-pages

zazzle:
    store:     'https://www.zazzle.com/pinedesigns?rf=238712509161080982&tc=pinedesignsgithubio'
newsletter:    'https://bit.ly/pine_designs_newsletter_01'
    
img:
    logo:             /public/img/pine-designs-logo-transparent.svg
    banner:           /public/img/pine-designs-banner.svg